[package]
name = "mishka"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.19", features = ["derive"] }
eyre = "0.6.8"
inquire = "0.6.2"
liquid = "0.26.4"
serde = { version = "1.0.175", features = ["derive"] }
toml = "0.7.6"
